{% set name = "webdataset" %}
{% set version = "0.2.73" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/webdataset-{{ version }}.tar.gz
  sha256: dc73c81326eff7e8060903d637d10c8c5ca9955e72b2fc240dd0cceb8c2e9f47

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - braceexpand
    - numpy
    - python >=3.6
    - pyyaml
    - pytorch

test:
  imports:
    - webdataset
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/webdataset/webdataset
  summary: Record sequential storage for deep learning.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - ap--
