{% set name = "webdataset" %}
{% set version = "0.2.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/webdataset-{{ version }}.tar.gz
  sha256: d89d1e2a399c0594a1be9a3794e0d97e0c509b1c6fd0d03de98522800c960588

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - braceexpand
    - numpy
    - python >=3.6
    - pyyaml
    - pytorch

test:
  imports:
    - webdataset
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/webdataset/webdataset
  summary: Record sequential storage for deep learning.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
