{% set name = "webdataset" %}
{% set version = "0.2.69" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/webdataset-{{ version }}.tar.gz
  sha256: 2319aaedc439d82f668dc4c95072f6de8b523a5dcd4d6c56d2ba81ec7b24ea7c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - braceexpand
    - numpy
    - python >=3.6
    - pyyaml
    - pytorch

test:
  imports:
    - webdataset
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/webdataset/webdataset
  summary: Record sequential storage for deep learning.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - ap--
