{% set name = "webdataset" %}
{% set version = "0.2.79" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/webdataset-{{ version }}.tar.gz
  sha256: a8ef8809e8c6b32423e40811a529b76a0799d93e3eba1bd1671640906a5fe138

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - braceexpand
    - numpy
    - python >=3.6
    - pyyaml
    - pytorch

test:
  imports:
    - webdataset
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/webdataset/webdataset
  summary: Record sequential storage for deep learning.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ap--
