{% set name = "webdataset" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/webdataset-{{ version }}.tar.gz
  sha256: 7f0498be827cfa46cc5430a58768a24e2c6a410676a61be1838f53d61afdaab4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=45
  run:
    - braceexpand
    - numpy
    - python >={{ python_min }}
    - pyyaml
    - pytorch

test:
  imports:
    - webdataset
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/webdataset/webdataset
  summary: Record sequential storage for deep learning.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ap--
